name: "✍️ ​​Suggest Changes"
description: Help us improve CS2.TEAM by suggesting changes.
labels: [suggestion]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve CS2.TEAM with your suggestions.
  - type: input
    id: url
    attributes:
      label: URL
      description: Please provide the URL of where you are suggesting changes to.
      placeholder: https://cs2.team
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions
      description: What changes would you like to suggest?
      placeholder: Enter your suggestions here.
    validations:
      required: true